# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '🚀 功能'
    labels:
      - '功能'
  - title: '🐛 Bug 修复'
    labels:
      - 'bug'
      - '修复'
  - title: '📝 文档更新'
    labels:
      - '文档'
  - title: '👻 优化'
    labels:
      - '优化'
  - title: '🚦 测试'
    labels:
      - '测试'
exclude-labels:
  - '重复'
  - '没有更改日志'
  - '无效'
  - 'good first issue'
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What’s Changed
  $CHANGES
Terms
Privacy
Security
